use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct Account {
    id: String,
    account_number: String,
    status: String,
    crypto_status: String,
    currency: String,
    buying_power: String,
    regt_buying_power: String,
    daytrading_buying_power: String,
    effective_buying_power: String,
    non_marginable_buying_power: String,
    bod_dtbp: String,
    cash: String,
    accrued_fees: String,
    pending_transfer_in: String,
    portfolio_value: String,
    pattern_day_trader: bool,
    trading_blocked: bool,
    transfers_blocked: bool,
    account_blocked: bool,
    created_at: String,
    trade_suspended_by_user: bool,
    multiplier: String,
    shorting_enabled: bool,
    equity: String,
    last_equity: String,
    long_market_value: String,
    short_market_value: String,
    position_market_value: String,
    initial_margin: String,
    maintenance_margin: String,
    last_maintenance_margin: String,
    sma: String,
    daytrade_count: i8,
    balance_asof: String,
    crypto_tier: i8,
}
